authapp/urls.py
from django.urls import path
from authapp import views

urlpatterns = [
    path('signup/',views.signup,name='signup'),
    path('login/',views.handleLogin,name='handleLogin'),
    path('logout/',views.handleLogout,name='handleLogout'),
   
]

portfolio/urls.py
from django.urls import path
from portfolio import views

urlpatterns = [
    path('',views.home,name='home'),
    path('about',views.about,name='about'),
    path('contact',views.contact,name='contact'),
    path('blog',views.handleblog,name='handleblog'),
    path('skills',views.skills,name='skills'),
    path('internshipdetails',views.internshipdetails,name='internshipdetails'),
    
]

project/urls.py
from os import stat
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('portfolio.urls')),
    path('auth/',include('authapp.urls')),
  
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

authapp/models.py
from django.db import models

# Create your models here.

portfolio/models.py
from django.db import models
from django.db.models.base import Model

# Create your models here.
class Contact(models.Model):
    name=models.CharField(max_length=25)
    email=models.EmailField()
    phonenumber=models.CharField(max_length=10)
    description=models.TextField()

    def __str__(self):
        return self.name
    

    # SKILLS SECTION

class Category(models.Model):
    name = models.CharField(max_length=20)

    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Skill'
        verbose_name_plural = 'Skills'

    def __str__(self):
        return self.name

class Skills(models.Model):
    category = models.ForeignKey(Category,
                                on_delete=models.CASCADE)
    skill_name = models.CharField(max_length=20)


class Blogs(models.Model):
    title=models.CharField(max_length=60)
    description=models.TextField()
    authname=models.CharField(max_length=15)
    img=models.ImageField(upload_to='blog',blank=True,null=True)
    timeStamp=models.DateTimeField(auto_now_add=True,blank=True)

    def __str__(self):
        return self.title

class Internship(models.Model):
    fullname=models.CharField(max_length=60)
    usn=models.CharField(max_length=60)
    email=models.CharField(max_length=60)
    college_name=models.CharField(max_length=100)
    offer_status=models.CharField(max_length=60)
    start_date=models.CharField(max_length=60)
    end_date=models.CharField(max_length=60)
    proj_report=models.CharField(max_length=60)
    timeStamp=models.DateTimeField(auto_now_add=True,blank=True)
    def __str__(self):
        return self.usn

authapp/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from django.contrib import messages

# Create your views here.
def signup(request):
    
    if request.method=="POST":
        get_email=request.POST.get('email')
        get_password=request.POST.get('pass1')
        get_confirm_password=request.POST.get('pass2')
        if get_password!=get_confirm_password:
            messages.info(request,'Password is not matching')
            return redirect('/auth/signup/')
        
        try:
            if User.objects.get(username=get_email):
                messages.warning(request,"Email is Taken")
                return redirect('/auth/signup/')
        except Exception as identifier:
            pass
        myuser=User.objects.create_user(get_email,get_email,get_password)
        myuser.save()

        myuser= authenticate(username=get_email,password=get_password)

        if myuser is not None:

            login(request,myuser)
            messages.success(request,"User Created & Login Success")
            return redirect('/')

        
    return render(request,'signup.html')

def handleLogin(request):
    if request.method=="POST":
        get_email=request.POST.get('email')
        get_password=request.POST.get('pass1')
        myuser= authenticate(username=get_email,password=get_password)

        if myuser is not None:
            login(request,myuser)
            messages.success(request,"Login Success")
            return redirect('/')
        else:
            messages.error(request,"Invalid Credentials")
    return render(request,'login.html')

def handleLogout(request):
    logout(request)
    messages.success(request,'logout success')
    return render(request,'login.html')

portfolio/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from portfolio.models import Contact,Blogs,Internship,Skills,Category
# Create your views here.
def home(request):
    return render(request,'home.html')

def handleblog(request):
    posts=Blogs.objects.all()
    context={"posts":posts}
    return render(request,'handleblog.html',context)


def about(request):
    return render(request,'about.html')

#skills
def skills(request):
    categories = Category.objects.all()
    context={"categories":categories}
    return render(request,'skills.html',context)



def internshipdetails(request):

    if not request.user.is_authenticated:
        messages.warning(request,"Please login to access this page")
        return redirect("/auth/login/")

    if request.method=="POST":
        fname=request.POST.get('name')
        femail=request.POST.get('email')
        fusn=request.POST.get('usn')
        fcollege=request.POST.get('cname')
        foffer=request.POST.get('offer')
        fstartdate=request.POST.get('startdate')
        fenddate=request.POST.get('enddate')
        fprojreport=request.POST.get('projreport')

# converting to upper case
        fname=fname.upper()
        fusn=fusn.upper()
        fcollege=fcollege.upper()
        fprojreport=fprojreport.upper()
        foffer=foffer.upper()

        # 
        check1=Internship.objects.filter(usn=fusn)
        check2=Internship.objects.filter(email=femail)

        if check1 or check2:
            messages.warning(request,"Your Details are Stored Already")
            return redirect("/internshipdetails")
        



        query=Internship(fullname=fname,usn=fusn,email=femail,college_name=fcollege,offer_status=foffer,start_date=fstartdate,end_date=fenddate,proj_report=fprojreport)
        query.save()

        messages.success(request,"Form is Submitted Successful!")
        return redirect('/internshipdetails')

    return render(request,'intern.html')

def contact(request):
    if request.method=="POST":
        fname=request.POST.get('name')
        femail=request.POST.get('email')
        fphoneno=request.POST.get('num')
        fdesc=request.POST.get('desc')
        query=Contact(name=fname,email=femail,phonenumber=fphoneno,description=fdesc)
        query.save()
        messages.success(request,"Thanks for contacting us. We will get by you Soon!")

        return redirect('/contact')

    return render(request,'contact.html')

templates/about.html
{% extends 'basic.html' %}
{% block title %} About {% endblock title %}
{% block body %}
{% load static %}
 <section id="about" class="about">
      <div class="container">

        <div class="section-title">
          <h2>About</h2>
          <p>Magnam dolores commodi suscipit. Necessitatibus eius consequatur ex aliquid fuga eum quidem. Sit sint consectetur velit. Quisquam quos quisquam cupiditate. Et nemo qui impedit suscipit alias ea. Quia fugiat sit in iste officiis commodi quidem hic quas.</p>
        </div>

        <div class="row">
          <div class="col-lg-4" data-aos="fade-right">
            <img src="{% static 'assets/img/Mica.jpg' %}" class="img-fluid" alt="">
          </div>
          <div class="col-lg-8 pt-4 pt-lg-0 content" data-aos="fade-left">
            <h3>Software Developer &amp; Software Tester.</h3>
            <p class="fst-italic">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore
              magna aliqua.
            </p>
            <div class="row">
              <div class="col-lg-6">
                <ul>
                  <li><i class="bi bi-chevron-right"></i> <strong>Birthday:</strong> <span>10 October 1998</span></li>
                  <li><i class="bi bi-chevron-right"></i> <strong>Website:</strong> <span>www.example.com</span></li>
                  <li><i class="bi bi-chevron-right"></i> <strong>Phone:</strong> <span>+276 793 91835</span></li>
                  <li><i class="bi bi-chevron-right"></i> <strong>City:</strong> <span>Cape Town</span></li>
                </ul>
              </div>
              <div class="col-lg-6">
                <ul>
                  <li><i class="bi bi-chevron-right"></i> <strong>Age:</strong> <span>30</span></li>
                  <li><i class="bi bi-chevron-right"></i> <strong>Degree:</strong> <span>Master</span></li>
                  <li><i class="bi bi-chevron-right"></i> <strong>PhEmailone:</strong> <span>email@example.com</span></li>
                  <li><i class="bi bi-chevron-right"></i> <strong>Freelance:</strong> <span>Available</span></li>
                </ul>
              </div>
            </div>
            <p>
              Officiis eligendi itaque labore et dolorum mollitia officiis optio vero. Quisquam sunt adipisci omnis et ut. Nulla accusantium dolor incidunt officia tempore. Et eius omnis.
              Cupiditate ut dicta maxime officiis quidem quia. Sed et consectetur qui quia repellendus itaque neque. Aliquid amet quidem ut quaerat cupiditate. Ab et eum qui repellendus omnis culpa magni laudantium dolores.
            </p>
          </div>
        </div>

      </div>
    </section><!-- End About Section -->

{% endblock body %}

templates/basic.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>
  {% block title %}{% endblock title %}
  
  </title>
  <meta content="" name="description">
  <meta content="" name="keywords">


  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
{% block stylecss %}

{% endblock stylecss %}

</head>

<body>

  <!-- ======= Mobile nav toggle button ======= -->
  <i class="bi bi-list mobile-nav-toggle d-xl-none"></i>

  <!-- ======= Header ======= -->
  <header id="header">
    <div class="d-flex flex-column">

      <div class="profile">
        <img src="{% static 'assets/img/Mica.jpg' %}" alt="" class="img-fluid rounded-circle">
        <h1 class="text-light"><a href="index.html">Welcome {{user.username}}</a></h1>
        <div class="social-links mt-3 text-center">
          <a href="https://twitter.com/MicaYonela" target="_blank" class="twitter"><i class="bx bxl-twitter"></i>
          <a href="https://www.instagram.com/mica_yonela" target="_blank" class="instagram"><i class="bx bxl-instagram"></i></a>
          <a href="https://github.com/yonelamica" target="_blank" class="github"><i class="bx bxl-github"></i></a>
          <a href="https://www.linkedin.com/in/yonela-mica-779390258" target="_blank" class="linkedin"><i class="bx bxl-linkedin"></i></a>
        </div>
      </div>

      <nav id="navbar" class="nav-menu navbar">
        <ul>
          <li><a href="/" class="nav-link scrollto active"><i class="bx bx-home"></i> <span>Home</span></a></li>
          <li><a href="/about" class="nav-link scrollto"><i class="bx bx-user"></i> <span>About</span></a></li>
       
          <li><a href="/blog" class="nav-link scrollto"><i class="bx bx-book-content"></i> <span>Blog</span></a></li>
          <li><a href="/skills" class="nav-link scrollto"><i class="bx bx-envelope"></i> <span>Skills</span></a></li>
        
          <li><a href="/contact" class="nav-link scrollto"><i class="bx bx-envelope"></i> <span>Contact</span></a></li>

          <!--<li><a href="/internshipdetails" class="nav-link scrollto"><i class="bx bx-envelope"></i> <span>Internship Form</span></a></li>-->

{% if not request.user.is_authenticated %}

     <li><a href="/auth/signup/" class="nav-link scrollto"><i class="bx bx-user"></i> <span>SignUp</span></a></li>

          <li><a href="/auth/login/" class="nav-link scrollto"><i class="bx bx-user"></i> <span>Login</span></a></li>
{% else %}

          <li><a href="/auth/logout/" class="nav-link scrollto"><i class="bx bx-user"></i> <span>Logout</span></a></li>
{% endif %}



     



        </ul>
      </nav><!-- .nav-menu -->
    </div>
  </header><!-- End Header -->

{% block hero %}


{% endblock hero %}


  <main id="main">
  {% block body %}
  
  {% endblock body %}

  </main>

  <!-- ======= Footer ======= -->
  <footer id="footer">
    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong><span>Yonela Mica</span></strong>
      </div>
      <div class="credits">
       
        Designed by <a href="">Y.M.M</a>
      </div>
    </div>
  </footer><!-- End  Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->

{% block scripts %}

{% endblock scripts %}



  <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>
  <script src="{% static 'assets/vendor/purecounter/purecounter.js' %}"></script>
  <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/typed.js/typed.min.js' %}"></script>
  <script src="{% static 'assets/vendor/waypoints/noframework.waypoints.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>

</body>

</html>

templates/contact.html
{% extends 'basic.html' %} 
{% block title %} Contact{% endblock title %}
{% block stylecss %}
<link
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
  integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ=="
  crossorigin="anonymous"
  referrerpolicy="no-referrer"
/>
{% endblock stylecss %} 
{% block body %}

<div class="container mt-4 p-2">
  <div class="row">
    <div class="col-md-4"></div>

    <div class="col-md-4">
    <br>
    <br>
    <br>
    
      <h3 class="text-white bg-dark text-center p-3">Contact Me</h3>

{% for message in messages %}

<div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
  <strong>{{message}} </strong> 
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}

      <div class="card p-2">


      <form action="/contact" method="post">{% csrf_token %}
        <div class="form-group">
          <h5>
            <span><i class="fas fa-user"></i> Name</span>
          </h5>
          <input type="text" class="form-control mb-3" name="name" required/>
        </div>
        <div class="form-group">
          <h5>
            <span><i class="bx bx-envelope"></i> Email</span>
          </h5>
          <input type="email" value="{{user.email}}" class="form-control mb-3" name="email" required/>
        </div>
        <div class="form-group">
          <h5>
            <span><i class="fas fa-phone-alt"></i> Phone No.</span>
          </h5>
          <input type="number" class="form-control mb-3" name="num" required/>
        </div>

        <div class="form-group">
          <h5>
            <span><i class="far fa-question-circle"></i>How can i help you </span>
          </h5>
          <textarea type="text" class="form-control mb-3" name="desc" required ></textarea>
        </div>
       


        <div class="d-grid gap-2">
          <button class="btn btn-dark" type="submit">Submit</button>
        </div>
     
      </div>

      </form>
    </div>

    <div class="col-md-4"></div>
  </div>
</div>

{% endblock body %}

templates/handleblog.html
{% extends 'basic.html' %} 
{% block title %} Blog{% endblock title %}

{% block body %} 
{% load static %}
<section id="services" class="services">
      <div class="container">

        <div class="section-title">
          <h2>Welcome to My Blog</h2>
         
        </div>

        <div class="row">

{% for post in posts reversed %}

          <div class="col-lg-4 col-md-6 icon-box" data-aos="fade-up">

            <div class="col-lg-4" data-aos="fade-right">
            <img src="{{post.img.url}}" class="img-fluid" alt="no-image">
          </div>
          <br>

            <div class="icon"><i class="bi bi-briefcase"></i></div>
            <h4 class="title"><a href="">{{post.title}}</a></h4>

            <p class="description">{{post.description}}</p>
            <h6>Posted By : <b>{{post.authname}} </b></h6>
            <p>Posted on : <b>{{post.timeStamp}} </b></p>
          </div>

{% endfor %}


         
         
        </div>

      </div>
    </section><!-- End Services Section -->
{% endblock body %}

templates/home.html
{% extends 'basic.html' %}
{% block title %} My Portfolio | Website {% endblock title %}
{% block hero %}
  <section id="hero" class="d-flex flex-column justify-content-center align-items-center">
    <div class="hero-container" data-aos="fade-in">
      <h1>Yonela Mica Mrubata</h1>
      <p>I'm a <span class="typed" data-typed-items="Software Developer, Software Tester, Freelancer"></span></p>
    </div>
  </section>

{% endblock hero %}
{% block body %}

{% for message in messages %}

<div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
  <strong>{{message}} </strong> 
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}

{% endblock body %}

templates/intern.html
{% extends 'basic.html' %} 
{% block title %} Internship details {% endblock title %}
{% block stylecss %}
<link
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
  integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ=="
  crossorigin="anonymous"
  referrerpolicy="no-referrer"
/>
{% endblock stylecss %} 
{% block body %}

<div class="container mt-4 p-2">
  <div class="row">
    <div class="col-md-4"></div>

    <div class="col-md-4">

    
      <h3 class="text-white bg-dark text-center p-3">Please fill out your Details Carefully</h3>

{% for message in messages %}

<div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
  <strong>{{message}} </strong> 
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}

      <div class="card p-2">


      <form action="/internshipdetails" method="post">{% csrf_token %}
        <div class="form-group">
          <h5>
            <span><i class="fas fa-user"></i> Full Name</span>
          </h5>
          <input type="text" class="form-control mb-3" name="name" required/>
        </div>
        <div class="form-group">
          <h5>
            <span><i class="fas fa-user"></i>U.S.N</span>
          </h5>
          <input type="text" class="form-control mb-3" name="usn" required/>
        </div>
        <div class="form-group">
          <h5>
            <span><i class="bx bx-envelope"></i> Email</span>
          </h5>
          <input type="email" value="{{user.email}}" class="form-control mb-3" name="email" required/>
        </div>

         <div class="form-group">
          <h5>
            <span><i class="far fa-question-circle"></i>Did you Received Offer Letter</span>
          </h5>
          <input type="text" class="form-control mb-3" name="offer" placeholder="Yes/No" required/>
        </div>
      

      <div class="form-group">
          <h5>
            <span><i class="far fa-calendar-check"></i>Start Date</span>
          </h5>
          <input type="date" class="form-control mb-3" name="startdate" required/>
        </div>

      <div class="form-group">
          <h5>
            <span><i class="far fa-calendar-check"></i>End Date</span>
          </h5>
          <input type="date" class="form-control mb-3" name="enddate" required/>
        </div>

        <div class="form-group">
          <h5>
            <span><i class="far fa-question-circle"></i>Did you want Project and Report</span>
          </h5>
          <input type="text" class="form-control mb-3" name="projreport" placeholder="Yes/No" required/>
        </div>

        <div class="form-group">
          <h5>
            <span><i class="far fa-question-circle"></i>College Name </span>
          </h5>
          <textarea type="text" class="form-control mb-3" name="cname" required ></textarea>
        </div>
       


        <div class="d-grid gap-2">
          <button class="btn btn-dark" type="submit">Submit</button>
        </div>
     
      </div>

      </form>
    </div>

    <div class="col-md-4"></div>
  </div>
</div>

{% endblock body %}

templates/login.html
{% extends 'basic.html' %} 
{% block title %} Login{% endblock title %}
{% block stylecss %}
<link
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
  integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ=="
  crossorigin="anonymous"
  referrerpolicy="no-referrer"
/>
{% endblock stylecss %} 
{% block body %}

<div class="container mt-4 p-2">
  <div class="row">
    <div class="col-md-4"></div>

    <div class="col-md-4">
    <br>
    <br>
    <br>
    
      <h3 class="text-white bg-dark text-center p-3">Login</h3>

{% for message in messages %}

<div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
  <strong>{{message}} </strong> 
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}

      <div class="card p-2">


      <form action="/auth/login/" method="post">{% csrf_token %}
        <div class="form-group">
          <h5>
            <span><i class="bx bx-envelope"></i> Email</span>
          </h5>
          <input type="email" class="form-control mb-3" name="email" required/>
        </div>

        <div class="form-group">
          <h5>
            <span><i class="fas fa-key"></i> Password</span>
          </h5>
          <input type="password" class="form-control mb-3" name="pass1" required />
        </div>

      

        <div class="d-grid gap-2">
          <button class="btn btn-dark" type="submit">Login</button>
        </div>
        <br>
      New User ? <a href="/auth/signup/">SignUp</a>
      </div>

      </form>
    </div>

    <div class="col-md-4"></div>
  </div>
</div>

{% endblock body %}

templates/signup.html
{% extends 'basic.html' %} 
{% block title %} Sign-Up {% endblock title %}
{% block stylecss %}
<link
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
  integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ=="
  crossorigin="anonymous"
  referrerpolicy="no-referrer"
/>
{% endblock stylecss %} 
{% block body %}

<div class="container mt-4 p-2">
  <div class="row">
    <div class="col-md-4"></div>

    <div class="col-md-4">
    <br>
    <br>
    <br>
    <br>
      <h3 class="text-white bg-dark text-center p-3">Sign Up Here</h3>
{% for message in messages %}

<div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
  <strong>{{message}} </strong> 
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
      <div class="card p-2">

      <form action="/auth/signup/" method="post">{% csrf_token %}
        <div class="form-group">
          <h5>
            <span><i class="bx bx-envelope"></i> Email</span>
          </h5>
          <input type="text" class="form-control mb-3" name="email" required/>
        </div>

        <div class="form-group">
          <h5>
            <span><i class="fas fa-key"></i> Password</span>
          </h5>
          <input type="password" class="form-control mb-3" name="pass1" required />
        </div>

        <div class="form-group">
          <h5>
            <span><i class="fas fa-lock"></i> Confirm Password</span>
          </h5>
          <input type="password" class="form-control mb-3" name="pass2" required/>
        </div>

        <div class="d-grid gap-2">
          <button class="btn btn-dark" type="submit">SignUp</button>
        </div>
          <br>
      Already User ? <a href="/auth/login/">Login</a>
      </div>
      
      </form>
    
    </div>

    <div class="col-md-4"></div>
  </div>
</div>

{% endblock body %}

templates/skills.html
{% extends 'basic.html' %}
{% block title %} Skills {% endblock title %}
{% block body %}
{% load static %}
<!--===== SKILLS =====-->
           
            <section class="skills section" id="skills">
                <h2 class="section-title">Skills</h2>

                <div class="skills__container bd-grid">
                    <div class="skills__box">
                        {% for category in categories %}
                        <h3 class="skills__subtitle">{{category.name}}</h3>
                            {% for skills in category.skills_set.all %}
                            
                                <span class="skills__name">{{skills.skill_name}}</span>
                            {% endfor %}
                        {% endfor %}
                        
                    </div>

                    <div class="skills__img">
                        <img src="{% static 'assets/img/skill.jpg' %}" alt="">
                    </div>
                </div>
            </section>

            {% endblock body %}

   